CREATE TABLE users (
                       id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       login        VARCHAR(50) UNIQUE NOT NULL,
                       password     VARCHAR(100) NOT NULL,
                       full_name    VARCHAR(255),
                       gender       VARCHAR(50), -- Пол, изначально был в clients
                       email        VARCHAR(100),
                       social_media VARCHAR(15),
                       notes        VARCHAR(255),
                       position     VARCHAR(50), -- Должность, изначально была в employees
                       role         VARCHAR(20) CHECK (role IN ('CLIENT', 'EMPLOYEE')) NOT NULL,
                       PRIMARY KEY (id)
);

CREATE TABLE orders (
                        id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        status     VARCHAR(20) CHECK (status IN ('ACTIVE', 'CANCELED', 'COMPLETED')),
                        details    VARCHAR(255),
                        order_date DATE DEFAULT CURRENT_DATE,
                        user_id    BIGINT NOT NULL,
                        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
                        PRIMARY KEY (id)
);